version: "3.7"

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - primary

  faye:
    build: .
    links:
      - redis
    depends_on:
      - redis
    restart: always
    ports:
      - 4242:4242
    env_file:
      - .faye.env.development
    networks:
      - primary


networks:
  primary: